/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    StoryChain: {
      address: "0x700b6a60ce7eaaea56f065753d8dcb9653dbad35",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "DEFAULT_STORY_DEPOSIT",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "FORK_FEE_AUTHOR",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "FORK_FEE_CHAPTER_AUTHOR",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "FREE_STORY_COUNT",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MIN_CHAPTERS_FOR_DEPOSIT",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "addComment",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "ipfsHash",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "chaptersMap",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "parentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "storyId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "author",
              type: "address",
              internalType: "address",
            },
            {
              name: "ipfsHash",
              type: "string",
              internalType: "string",
            },
            {
              name: "createdTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "likes",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "forkCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "forkFee",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalForkFees",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalTips",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalTipCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "chapterNumber",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "comments",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "commenter",
              type: "address",
              internalType: "address",
            },
            {
              name: "ipfsHash",
              type: "string",
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "createChapter",
          inputs: [
            {
              name: "storyId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "parentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "ipfsHash",
              type: "string",
              internalType: "string",
            },
            {
              name: "forkFee",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createStory",
          inputs: [
            {
              name: "ipfsHash",
              type: "string",
              internalType: "string",
            },
            {
              name: "forkFee",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "forkStory",
          inputs: [
            {
              name: "storyId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "parentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "ipfsHash",
              type: "string",
              internalType: "string",
            },
            {
              name: "forkFee",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "getApproved",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getChapter",
          inputs: [
            {
              name: "chapterId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct StoryChain.Chapter",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "parentId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "storyId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "author",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "ipfsHash",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "createdTime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "likes",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "forkCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "forkFee",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "totalForkFees",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "totalTips",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "totalTipCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "chapterNumber",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "childChapterIds",
                  type: "uint256[]",
                  internalType: "uint256[]",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getStory",
          inputs: [
            {
              name: "storyId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct StoryChain.Story",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "author",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "ipfsHash",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "createdTime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "likes",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "forkCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "forkFee",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "isDeposited",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "deposited",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "totalTips",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "totalTipCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "totalForkFees",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "firstChapterId",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getStoryDeposit",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasLiked",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isApprovedForAll",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "likeChapter",
          inputs: [
            {
              name: "chapterId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "likeStory",
          inputs: [
            {
              name: "storyId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ownerOf",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pendingWithdrawals",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "safeTransferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "safeTransferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "data",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setApprovalForAll",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
            {
              name: "approved",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "stories",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "storiesMap",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "author",
              type: "address",
              internalType: "address",
            },
            {
              name: "ipfsHash",
              type: "string",
              internalType: "string",
            },
            {
              name: "createdTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "likes",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "forkCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "forkFee",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "isDeposited",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "deposited",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalTips",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalTipCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalForkFees",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "firstChapterId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "supportsInterface",
          inputs: [
            {
              name: "interfaceId",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "tip",
          inputs: [
            {
              name: "storyId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "chapterId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "tokenURI",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "updateChapterForkFee",
          inputs: [
            {
              name: "chapterId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "newForkFee",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "updateStoryDeposit",
          inputs: [
            {
              name: "newDeposit",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "updateStoryForkFee",
          inputs: [
            {
              name: "storyId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "newForkFee",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawRewards",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "approved",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ApprovalForAll",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "operator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "approved",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "BatchMetadataUpdate",
          inputs: [
            {
              name: "_fromTokenId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "_toTokenId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ChapterCreated",
          inputs: [
            {
              name: "storyId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "chapterId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "parentId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "author",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "ipfsHash",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ChapterForked",
          inputs: [
            {
              name: "storyId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "chapterId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "parentId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "author",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "ipfsHash",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ChapterLiked",
          inputs: [
            {
              name: "chapterId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "liker",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newLikeCount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ChapterRewardsDistributed",
          inputs: [
            {
              name: "chapterId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "chapterAuthor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "CommentAdded",
          inputs: [
            {
              name: "chapterId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "commenter",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "DepositRefunded",
          inputs: [
            {
              name: "storyId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "author",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MetadataUpdate",
          inputs: [
            {
              name: "_tokenId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RewardsWithdrawn",
          inputs: [
            {
              name: "user",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "StoryCreated",
          inputs: [
            {
              name: "storyId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "author",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "ipfsHash",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "StoryLiked",
          inputs: [
            {
              name: "storyId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "liker",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newLikeCount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "StoryRewardsDistributed",
          inputs: [
            {
              name: "storyId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "storyAuthor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "tipSent",
          inputs: [
            {
              name: "storyId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "chapterId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "tipper",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ERC721IncorrectOwner",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InsufficientApproval",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidApprover",
          inputs: [
            {
              name: "approver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidOperator",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidReceiver",
          inputs: [
            {
              name: "receiver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidSender",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721NonexistentToken",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
