"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

type Language = "zh" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 中文翻译
const zhTranslations: Record<string, string> = {
  // 导航
  "nav.home": "首页",
  "nav.create": "创建故事",
  "nav.explore": "探索",
  "nav.debug": "合约调试",
  "nav.profile": "个人中心",

  // 站点标题
  "site.title": "StoryChain",
  "site.subtitle": "去中心化故事平台",

  // 主页
  "welcome.to": "欢迎来到",
  "welcome.title": "StoryChain",
  "welcome.subtitle": "去中心化故事创作平台",
  "welcome.description":
    "在这里，每个故事都可以分叉成无限的可能性。创建、续写、分叉故事，与全世界的创作者一起构建故事宇宙。",
  "welcome.get_started": "开始创作",
  "welcome.explore_stories": "探索故事",
  "welcome.connect_wallet": "连接钱包",
  "welcome.connected_address": "已连接地址",

  // 故事相关
  "story.create": "创建故事",
  "story.title": "故事标题",
  "story.content": "故事内容",
  "story.fork_fee": "分叉费用",
  "story.create_story": "创建故事",
  "story.add_chapter": "添加章节",
  "story.fork_story": "分叉故事",
  "story.like": "点赞",
  "story.comment": "评论",
  "story.tip": "打赏",
  "story.author": "作者",
  "story.created_time": "创建时间",
  "story.likes": "点赞数",
  "story.forks": "分叉数",
  "story.tips": "打赏收入",
  "story.chapter": "章节",
  "story.parent_chapter": "父章节",

  // 按钮和操作
  "button.create": "创建",
  "button.read": "阅读",
  "button.save": "保存",
  "button.cancel": "取消",
  "button.submit": "提交",
  "button.upload": "上传",
  "button.download": "下载",
  "button.edit": "编辑",
  "button.delete": "删除",
  "button.confirm": "确认",
  "button.back": "返回",
  "button.next": "下一步",
  "button.previous": "上一步",
  "button.refresh": "刷新",

  // 表单
  "form.title.required": "标题必填",
  "form.content.required": "内容必填",
  "form.fee.invalid": "费用格式错误",
  "form.upload_image": "上传图片",
  "form.upload_file": "上传文件",

  // 状态提示
  loading: "加载中...",
  uploading: "上传中...",
  success: "操作成功",
  error: "操作失败",
  connecting: "连接中...",
  connected: "已连接",
  disconnected: "未连接",

  // 主题切换
  "theme.light": "浅色模式",
  "theme.dark": "深色模式",
  "theme.toggle": "切换主题",

  // 语言切换
  "language.zh": "中文",
  "language.en": "English",
  "language.toggle": "切换语言",

  // IPFS相关
  "ipfs.uploading": "上传到IPFS中...",
  "ipfs.uploaded": "已上传到IPFS",
  "ipfs.error": "IPFS上传失败",

  // 交易相关
  "transaction.pending": "交易等待确认",
  "transaction.confirmed": "交易已确认",
  "transaction.failed": "交易失败",
  "transaction.hash": "交易哈希",

  // 钱包相关
  "wallet.connect": "连接钱包",
  "wallet.disconnect": "断开连接",
  "wallet.account": "账户",
  "wallet.balance": "余额",
  "wallet.network": "网络",

  // 错误信息
  "error.network": "网络错误",
  "error.wallet": "钱包错误",
  "error.contract": "合约调用错误",
  "error.ipfs": "IPFS错误",
  "error.unknown": "未知错误",
  "error.missing_parameters": "缺少必要的参数",

  // 成功信息
  "success.story_created": "故事创建成功！",
  "success.chapter_added": "章节添加成功！",
  "success.story_forked": "故事分叉成功！",
  "success.liked": "点赞成功！",
  "success.tipped": "打赏成功！",
  "success.comment_added": "评论添加成功！",

  // 个人中心页面
  "profile.title": "我的创作中心",
  "profile.address": "地址",
  "profile.pending_rewards": "待提取奖励",
  "profile.stories": "故事",
  "profile.chapters": "章节",
  "profile.likes": "获赞",
  "profile.forks": "被分叉",
  "profile.my_stories": "我的故事",
  "profile.my_chapters": "我的章节",
  "profile.statistics": "统计信息",
  "profile.withdraw": "提取",
  "profile.empty_stories": "还没有创建任何故事",
  "profile.empty_chapters": "还没有创建任何章节",
  "profile.load_failed": "加载失败",
  "profile.retry": "重试",
  "profile.create_new_story": "创建新故事",
  "profile.view": "查看",
  "profile.view_story": "查看故事",
  "profile.no_stories": "还没有创建故事",
  "profile.no_chapters": "还没有创建章节",
  "profile.start_creating": "开始你的第一个创作吧！",
  "profile.explore_and_create": "为你的故事或他人的故事添加章节吧！",
  "profile.explore_stories": "探索故事",
  "profile.create_story": "创建故事",
  "profile.detailed_stats": "详细统计",
  "profile.creation_stats": "创作统计",
  "profile.interaction_stats": "互动统计",
  "profile.revenue_stats": "收益统计",
  "profile.total_stories": "总故事数",
  "profile.total_chapters": "总章节数",
  "profile.avg_chapters_per_story": "平均章节/故事",
  "profile.total_likes": "总点赞数",
  "profile.times_forked": "被分叉次数",
  "profile.pending_rewards_stat": "待提取奖励",
  "profile.tip_revenue": "打赏收益",
  "profile.fork_revenue": "分叉收益",
  "profile.total_revenue": "总收益",
  "profile.withdrawn": "已提取",
  "profile.chapter_num": "第{number}章",

  // 故事详情页面
  "story.detail.loading": "加载故事中...",
  "story.detail.not_found": "故事不存在",
  "story.detail.chapters": "章节",
  "story.detail.chapter_tree": "章节树",
  "story.detail.fork_point": "故事分叉点",
  "story.detail.continue": "续写",
  "story.detail.fork": "分叉",
  "story.detail.read": "阅读",
  "story.detail.back_to_story": "返回故事",
  "story.detail.previous_chapter": "上一章",
  "story.detail.next_chapter": "下一章",

  // 章节页面
  "chapter.loading": "加载章节中...",
  "chapter.not_found": "章节不存在",
  "chapter.number": "第 {number} 章",
  "chapter.previous": "上一章",
  "chapter.next": "下一章",

  // 创建页面
  "create.title": "创建你的专属故事",
  "create.subtitle": "每个故事都是独特的NFT。其他用户可以分叉你的故事创造新的分支。",
  "create.connect_wallet": "请先连接钱包才能创建故事",
  "create.basic_info": "基本信息",
  "create.story_title": "故事标题",
  "create.story_description": "故事描述",
  "create.tags": "标签",
  "create.story_cover": "故事封面",
  "create.creating": "创建中...",
  "create.title_placeholder": "输入吸引人的故事标题...",
  "create.description_placeholder": "简短描述你的故事...",
  "create.description_optional": "（可选）",
  "create.tags_separator": "（用逗号分隔）",
  "create.tags_placeholder": "科幻, 悬疑, 冒险...",

  // 探索页面
  "explore.title": "探索社区创作的精彩故事，发现无限的创意可能性",
  "explore.search": "搜索故事...",
  "explore.filter_by_author": "按作者筛选",
  "explore.loading": "加载中...",
  "explore.retry": "重试加载",
  "explore.no_stories": "暂无故事",
  "explore.search_placeholder": "搜索故事标题、描述、标签或作者地址...",
  "explore.search_results": "找到 {count} 个故事",
  "explore.search_contains": "包含 \"{term}\"",
  "explore.clear_search": "清空",
  "explore.clear_search_tooltip": "清空搜索 (Esc)",
  "explore.sort_by": "排序：",
  "explore.sort_latest": "最新创建",
  "explore.sort_popular": "最受欢迎",
  "explore.sort_tips": "最多打赏",
  "explore.total_stories": "共 {count} 个故事",
  "explore.load_error": "加载故事失败: {error}",
  "explore.retry_button": "重试",
  "explore.loading_stories": "正在加载故事...",
  "explore.story_alt": "故事 #{id}",
  "explore.error_load_failed": "加载故事信息失败: {error}",
  "explore.error_notification": "故事 #{id} 元数据加载失败",
  "explore.retry_load": "重试加载",
  "explore.read_button": "阅读",
  "explore.no_stories_found": "没有找到匹配的故事",
  "explore.search_suggestions": "尝试使用不同的关键词，或者",
  "explore.clear_conditions": "清空搜索条件",
  "explore.suggested_searches": "建议搜索：",
  "explore.tag_scifi": "科幻",
  "explore.tag_adventure": "冒险",
  "explore.tag_story": "故事",
  "explore.no_stories_yet": "还没有故事",
  "explore.be_first_creator": "成为第一个创建故事的人！",
  "explore.create_tooltip": "创建故事",

  // 分叉页面
  "fork.title": "基于现有章节创建新的故事分支",
  "fork.original_story": "原始故事",
  "fork.create_fork": "创建分叉",
  "fork.new_title": "新故事标题",
  "fork.new_content": "新故事内容",

  // 评论系统
  "comment.title": "评论",
  "comment.add": "发布评论",
  "comment.adding": "发布中...",
  "comment.connect_wallet": "请连接钱包后再发表评论",
  "comment.empty": "还没有评论，来发表第一个评论吧！",
  "comment.placeholder": "写下你的评论...",
  "comment.placeholder_story": "对这个故事说点什么...",
  "comment.placeholder_chapter": "对这个章节说点什么...",
  "comment.loading": "评论内容正在从IPFS加载...",

  // IPFS内容显示
  "ipfs.load_failed": "加载失败",
  "ipfs.load_content_failed": "加载 IPFS 内容失败",
  "ipfs.load_preview_failed": "加载预览失败",
  "ipfs.copy_cid": "复制 CID",
  "ipfs.copy_link": "复制链接",
  "ipfs.title_label": "标题",
  "ipfs.description_label": "描述",
  "ipfs.content_label": "内容",
  "ipfs.author_label": "作者",
  "ipfs.created_time_label": "创建时间",
  "ipfs.attributes_label": "属性",
  "ipfs.tags_label": "标签",

  // IPFS上传
  "upload.file_size_exceeded": "文件大小不能超过 {size}MB",
  "upload.upload_failed": "上传失败",
  "upload.click_or_drag": "点击上传或拖拽文件到此处",
  "upload.supported_types": "支持图片、文本、JSON 等文件类型",
  "upload.max_file_size": "最大文件大小: {size}MB",
  "upload.select_image_file": "请选择图片文件",
  "upload.image_size_exceeded": "图片大小不能超过 5MB",
  "upload.image_upload_failed": "图片上传失败",
  "upload.preview": "预览",
  "upload.image_formats": "PNG, JPG, GIF (最大 5MB)",

  // 点赞系统
  "like.liked": "已点赞",
  "like.like": "点赞",
  "like.connect_wallet": "请先连接钱包",

  // 打赏系统
  "tip.title": "打赏",
  "tip.amount": "打赏金额",
  "tip.send": "发送打赏",
  "tip.connect_wallet": "请先连接钱包",
  "tip.story": "打赏故事",
  "tip.chapter": "打赏章节",
  "tip.story_author": "故事作者",
  "tip.chapter_author": "章节作者",
  "tip.support_creation": "支持优质内容创作",
  "tip.select_amount": "选择打赏金额",
  "tip.custom_amount": "自定义金额",
  "tip.enter_amount": "输入金额...",
  "tip.fee_distribution": "费用分配:",
  "tip.author_receive": "{author}: {amount} STT",
  "tip.story_author_receive": "故事作者: {amount} STT",
  "tip.chapter_author_receive": "章节作者: {amount} STT",
  "tip.platform_fee": "平台手续费: {amount} STT",
  "tip.tipping": "打赏中...",
  "tip.success": "打赏成功！",
  "tip.failed": "打赏失败",

  // 首页功能卡片
  "home.feature1.title": "开启你的创作之旅。每个故事都是独特的NFT。",
  "home.feature2.title": "探索其他创作者的精彩故事，发现无限的创意可能性。",
  "home.feature3.title": "分叉喜欢的故事，创造属于你的故事分支和结局。",

  // 故事详情页面专用翻译键
  "story.detail.back": "返回",
  "story.detail.updating": "正在更新数据...",
  "story.detail.story_cover": "故事封面",
  "story.detail.story_tags": "故事标签",
  "story.detail.story_structure": "故事结构",
  "story.detail.total_chapters": "总章节",
  "story.detail.fork_points": "分叉点",
  "story.detail.tree_help": "点击节点可查看详细信息，使用操作按钮进行互动",
  "story.detail.no_chapters": "还没有章节",
  "story.detail.no_chapters_desc": "任何人都可以为这个故事添加第一章，开始精彩的故事之旅",
  "story.detail.add_first_chapter": "添加第一章",
  "story.detail.continue_first_chapter": "续写第一章",
  "story.detail.connect_wallet_desc": "连接钱包后即可添加第一章",
  "story.detail.continue_latest": "续写最新章节",
  "story.detail.fork_latest": "分叉最新章节",
  "story.detail.add_chapter_tooltip": "添加新章节（仅故事作者可操作）",
  "story.detail.continue_story": "续写故事",
  "story.detail.fork_story_button": "分叉故事",
  "story.detail.fork_story_tooltip": "基于这个故事创建分叉",
  "story.detail.connect_wallet_actions": "连接钱包后可续写章节或创建分叉",
  "story.detail.story_not_found": "故事不存在或加载失败",
  "story.detail.load_failed": "加载失败",
  "story.detail.retry": "重试",

  // 章节相关翻译键
  "chapter.title": "第 {number} 章",
  "chapter.author_label": "作者:",
  "chapter.fork_fee_label": "分叉费用: {fee} STT",
  "chapter.reading_detail": "点击阅读详细内容",
  "chapter.forks_count": "{count} 个分叉",
  "chapter.branches_count": "{count} 个分支",
  "chapter.story_fork_here": "故事在此分叉",
  "chapter.fork_description":
    "第 {number} 章之后有 {count} 个不同的发展方向，每个分支都带来不同的故事体验。选择你感兴趣的分支继续阅读：",
  "chapter.select_branch": "选择分支 ({count})",
  "chapter.branch_label": "分支 {letter}",
  "chapter.read_chapter": "阅读章节",
  "chapter.continue_chapter": "续写",
  "chapter.fork_chapter": "分叉",
  "chapter.tip_chapter": "打赏",
  "chapter.connect_wallet_tip": "请先连接钱包",
  "chapter.tip_tooltip": "给章节作者打赏",
  "chapter.continue_tooltip": "续写此章节",
  "chapter.fork_tooltip_base": "基于此章节创建分叉",
  "chapter.fork_tooltip_fee": "基于此章节创建分叉 (需支付 {fee} STT)",
  "chapter.fork_fee_badge": "{fee} STT",
  "chapter.only_author_continue": "只有章节作者可以续写自己的章节",
  "chapter.only_latest_continue": "只有最新章节才能续写",
  "chapter.continue_this_chapter": "续写此章节",
  "chapter.has_forks": "此章节有 {count} 个分叉",
  "chapter.loading_title": "⚠️ 章节标题加载中...",
  "chapter.loading_content": "正在加载章节标题...",
  "chapter.retry_loading": "重新加载章节信息",
  "chapter.loading_error_new": "新章节可能需要几分钟时间同步，请稍后再试",
  "chapter.info_loading": "📖 章节信息加载中...",
  "chapter.reloading": "正在重新加载章节信息...",

  // 模态框翻译键
  "modal.add_chapter.title": "添加新章节",
  "modal.add_chapter.chapter_title": "章节标题 *",
  "modal.add_chapter.chapter_content": "章节内容 *",
  "modal.add_chapter.title_placeholder": "输入章节标题...",
  "modal.add_chapter.content_placeholder": "继续你的故事...",
  "modal.add_chapter.fork_fee": "分叉费用",
  "modal.add_chapter.fork_fee_unit": "STT",
  "modal.add_chapter.chapter_image": "章节插图",
  "modal.add_chapter.creating": "创建中...",
  "modal.add_chapter.create": "创建章节",
  "modal.continue_chapter.title": "续写章节 - 第 {number} 章",
  "modal.continue_chapter.based_on": "基于章节：",
  "modal.continue_chapter.content_placeholder": "继续这个故事...",
  "modal.continue_chapter.fork_fee_desc": "STT (其他用户续写此章节时需支付)",
  "modal.continue_chapter.continuing": "续写中...",
  "modal.continue_chapter.continue": "续写章节",
  "modal.fork_chapter.title": "创建章节分叉",
  "modal.fork_chapter.fork_title": "分叉章节标题 *",
  "modal.fork_chapter.fork_content": "分叉内容 *",
  "modal.fork_chapter.title_placeholder": "输入分叉章节的标题...",
  "modal.fork_chapter.content_placeholder": "从这里开始你的分叉章节...",
  "modal.fork_chapter.fork_fee_desc": "STT (其他用户续写此分叉章节时需支付)",
  "modal.fork_chapter.chapter_note": "将创建一个新的章节分支，仍属于当前故事",
  "modal.fork_chapter.fee_required": "需要支付分叉费用",
  "modal.fork_chapter.fee_description": "分叉此章节需要支付 {fee} STT",
  "modal.fork_chapter.forking": "分叉中...",
  "modal.fork_chapter.fork_button": "创建章节分叉",
  "modal.fork_chapter.fork_button_fee": "支付 {fee} STT 并创建分叉",

  // 错误和成功消息
  "error.wallet_connect_required": "请先连接钱包",
  "error.title_content_required": "标题和内容不能为空",
  "error.chapter_not_exist": "章节不存在",
  "error.only_author_continue": "只有章节作者可以续写自己的章节",
  "error.chapter_create_failed": "创建失败",
  "error.chapter_continue_failed": "续写失败",
  "error.chapter_fork_failed": "分叉失败",
  "error.tip_failed": "打赏失败",
  "error.metadata_load_failed": "加载章节元数据失败",
  "success.chapter_created": "章节创建成功！",
  "success.chapter_continued": "章节续写成功！",
  "success.chapter_forked": "章节分叉成功！",
  "prompt.tip_amount": "请输入打赏金额 (STT):",
  "prompt.fork_confirm": "分叉此章节需要支付 {fee} STT 给原作者。确定要继续吗？",

  // 章节阅读页面专用翻译键
  "chapter.read.loading": "加载章节中...",
  "chapter.read.not_found": "章节不存在",
  "chapter.read.back_to_story": "返回故事",
  "chapter.read.previous": "上一章",
  "chapter.read.next": "下一章",
  "chapter.read.tip": "打赏",
  "chapter.read.continue": "续写",
  "chapter.read.fork": "分叉",
  "chapter.read.story_number": "故事 #{id}",
  "chapter.read.chapter_number": "第 {number} 章",
  "chapter.read.story_fork_point": "故事分叉点",
  "chapter.read.fork_description": "这里有 {count} 个不同的故事发展方向，选择一个继续阅读：",
  "chapter.read.branch_label": "分支 {number}",
  "chapter.read.current": "当前",
  "chapter.read.click_to_read": "点击阅读这个分支",
  "chapter.read.tip_earned": "{amount} STT",
  "chapter.read.next_branches": "下一章 ({count})",
  "chapter.read.invalid_content_id": "无效的内容标识",
  "chapter.read.content_empty": "内容为空",
  "chapter.read.load_content_failed": "加载内容失败",
  "chapter.read.chapter_image": "章节插图",
  "chapter.read.get_data_failed": "获取数据失败",
  "chapter.read.load_story_metadata_failed": "加载故事元数据失败",
  "chapter.read.get_chapters_failed": "获取章节数据失败",
  "chapter.read.connect_wallet_first": "请先连接钱包",
  "chapter.read.input_tip_amount": "输入打赏金额 (STT):",
  "chapter.read.tip_success": "打赏成功！",
  "chapter.read.tip_failed": "打赏失败",
  "chapter.read.return_to_story": "返回故事页面",
  "chapter.read.connect_wallet_tip": "请先连接钱包",
  "chapter.read.tip_author": "给章节作者打赏",

  // 分叉页面
  "fork.missing_story_id": "缺少故事ID参数",
  "fork.original_content_not_found": "原始内容不存在或加载失败",
  "fork.back": "返回",
  "fork.chapter_subtitle": "基于现有章节创建新的故事分支",
  "fork.story_subtitle": "基于现有故事创建新的故事线",
  "fork.fee_required_title": "需要支付分叉费用",
  "fork.fee_required_desc": "分叉此{type}需要支付 {fee} STT 给原作者",
  "fork.original_story": "原始故事",
  "fork.original_chapter": "原始章节",
  "fork.likes": "点赞",
  "fork.forks": "分叉",
  "fork.fork_fee_label": "分叉费",
  "fork.create_fork": "创建分叉",
  "fork.basic_info": "基本信息",
  "fork.fork_title": "分叉标题 *",
  "fork.fork_title_placeholder": "为你的分叉起个标题...",
  "fork.fork_content": "分叉内容 *",
  "fork.fork_content_placeholder": "继续这个故事...",
  "fork.characters": "字符",
  "fork.chapter_illustration": "章节插图",
  "fork.economic_settings": "经济设置",
  "fork.my_fork_fee": "我的分叉费用",
  "fork.fork_fee_description": "其他用户分叉你的内容时需要支付的费用",
  "fork.fee_distribution": "费用分配:",
  "fork.you_pay": "你需要支付: {fee} STT",
  "fork.story_author_gets": "原故事作者将获得: {amount} STT",
  "fork.chapter_author_gets": "原章节作者将获得: {amount} STT",
  "fork.platform_fee": "平台手续费: {amount} STT",
  "fork.forking": "分叉中...",
  "fork.create_fork_button": "创建分叉",
};

// 英文翻译
const enTranslations: Record<string, string> = {
  // Navigation
  "nav.home": "Home",
  "nav.create": "Create Story",
  "nav.explore": "Explore",
  "nav.debug": "Debug Contracts",
  "nav.profile": "Profile",

  // Site title
  "site.title": "StoryChain",
  "site.subtitle": "Decentralized Story Platform",

  // Home page
  "welcome.to": "Welcome to",
  "welcome.title": "StoryChain",
  "welcome.subtitle": "Decentralized Story Creation Platform",
  "welcome.description":
    "Here, every story can fork into infinite possibilities. Create, continue, and fork stories with creators worldwide to build a story universe.",
  "welcome.get_started": "Get Started",
  "welcome.explore_stories": "Explore Stories",
  "welcome.connect_wallet": "Connect Wallet",
  "welcome.connected_address": "Connected Address",

  // Story related
  "story.create": "Create Story",
  "story.title": "Story Title",
  "story.content": "Story Content",
  "story.fork_fee": "Fork Fee",
  "story.create_story": "Create Story",
  "story.add_chapter": "Add Chapter",
  "story.fork_story": "Fork Story",
  "story.like": "Like",
  "story.comment": "Comment",
  "story.tip": "Tip",
  "story.author": "Author",
  "story.created_time": "Created Time",
  "story.likes": "Likes",
  "story.forks": "Forks",
  "story.tips": "Tips Earned",
  "story.chapter": "Chapter",
  "story.parent_chapter": "Parent Chapter",

  // Buttons and actions
  "button.create": "Create",
  "button.read": "Read",
  "button.save": "Save",
  "button.cancel": "Cancel",
  "button.submit": "Submit",
  "button.upload": "Upload",
  "button.download": "Download",
  "button.edit": "Edit",
  "button.delete": "Delete",
  "button.confirm": "Confirm",
  "button.back": "Back",
  "button.next": "Next",
  "button.previous": "Previous",
  "button.refresh": "Refresh",

  // Form
  "form.title.required": "Title is required",
  "form.content.required": "Content is required",
  "form.fee.invalid": "Invalid fee format",
  "form.upload_image": "Upload Image",
  "form.upload_file": "Upload File",

  // Status messages
  loading: "Loading...",
  uploading: "Uploading...",
  success: "Success",
  error: "Error",
  connecting: "Connecting...",
  connected: "Connected",
  disconnected: "Disconnected",

  // Theme toggle
  "theme.light": "Light Mode",
  "theme.dark": "Dark Mode",
  "theme.toggle": "Toggle Theme",

  // Language toggle
  "language.zh": "中文",
  "language.en": "English",
  "language.toggle": "Toggle Language",

  // IPFS related
  "ipfs.uploading": "Uploading to IPFS...",
  "ipfs.uploaded": "Uploaded to IPFS",
  "ipfs.error": "IPFS upload failed",

  // Transaction related
  "transaction.pending": "Transaction pending",
  "transaction.confirmed": "Transaction confirmed",
  "transaction.failed": "Transaction failed",
  "transaction.hash": "Transaction Hash",

  // Wallet related
  "wallet.connect": "Connect Wallet",
  "wallet.disconnect": "Disconnect",
  "wallet.account": "Account",
  "wallet.balance": "Balance",
  "wallet.network": "Network",

  // Error messages
  "error.network": "Network error",
  "error.wallet": "Wallet error",
  "error.contract": "Contract call error",
  "error.ipfs": "IPFS error",
  "error.unknown": "Unknown error",
  "error.missing_parameters": "Missing required parameters",

  // Success messages
  "success.story_created": "Story created successfully!",
  "success.chapter_added": "Chapter added successfully!",
  "success.story_forked": "Story forked successfully!",
  "success.liked": "Liked successfully!",
  "success.tipped": "Tipped successfully!",
  "success.comment_added": "Comment added successfully!",

  // Profile page
  "profile.title": "My Creative Center",
  "profile.address": "Address",
  "profile.pending_rewards": "Pending Rewards",
  "profile.stories": "Stories",
  "profile.chapters": "Chapters",
  "profile.likes": "Likes",
  "profile.forks": "Forks",
  "profile.my_stories": "My Stories",
  "profile.my_chapters": "My Chapters",
  "profile.statistics": "Statistics",
  "profile.withdraw": "Withdraw",
  "profile.empty_stories": "No stories created yet",
  "profile.empty_chapters": "No chapters created yet",
  "profile.load_failed": "Load Failed",
  "profile.retry": "Retry",
  "profile.create_new_story": "Create New Story",
  "profile.view": "View",
  "profile.view_story": "View Story",
  "profile.no_stories": "No stories created yet",
  "profile.no_chapters": "No chapters created yet",
  "profile.start_creating": "Start your first creation!",
  "profile.explore_and_create": "Add chapters to your stories or others' stories!",
  "profile.explore_stories": "Explore Stories",
  "profile.create_story": "Create Story",
  "profile.detailed_stats": "Detailed Statistics",
  "profile.creation_stats": "Creation Statistics",
  "profile.interaction_stats": "Interaction Statistics",
  "profile.revenue_stats": "Revenue Statistics",
  "profile.total_stories": "Total Stories",
  "profile.total_chapters": "Total Chapters",
  "profile.avg_chapters_per_story": "Avg Chapters/Story",
  "profile.total_likes": "Total Likes",
  "profile.times_forked": "Times Forked",
  "profile.pending_rewards_stat": "Pending Rewards",
  "profile.tip_revenue": "Tip Revenue",
  "profile.fork_revenue": "Fork Revenue",
  "profile.total_revenue": "Total Revenue",
  "profile.withdrawn": "Withdrawn",
  "profile.chapter_num": "Chapter {number}",

  // Story detail page
  "story.detail.loading": "Loading story...",
  "story.detail.not_found": "Story not found",
  "story.detail.chapters": "Chapters",
  "story.detail.chapter_tree": "Chapter Tree",
  "story.detail.fork_point": "Story Fork Point",
  "story.detail.continue": "Continue",
  "story.detail.fork": "Fork",
  "story.detail.read": "Read",
  "story.detail.back_to_story": "Back to Story",
  "story.detail.previous_chapter": "Previous Chapter",
  "story.detail.next_chapter": "Next Chapter",

  // Chapter page
  "chapter.loading": "Loading chapter...",
  "chapter.not_found": "Chapter not found",
  "chapter.number": "Chapter {number}",
  "chapter.previous": "Previous",
  "chapter.next": "Next",

  // Create page
  "create.title": "Create Your Unique Story",
  "create.subtitle": "Each story is a unique NFT. Others can fork your story to create new branches.",
  "create.connect_wallet": "Please connect wallet to create story",
  "create.basic_info": "Basic Information",
  "create.story_title": "Story Title",
  "create.story_description": "Story Description",
  "create.tags": "Tags",
  "create.story_cover": "Story Cover",
  "create.creating": "Creating...",
  "create.title_placeholder": "Enter an attractive story title...",
  "create.description_placeholder": "Brief description of your story...",
  "create.description_optional": "(Optional)",
  "create.tags_separator": "(Separated by commas)",
  "create.tags_placeholder": "Sci-fi, Mystery, Adventure...",

  // Explore page
  "explore.title": "Explore amazing stories created by the community, discover infinite creative possibilities",
  "explore.search": "Search stories...",
  "explore.filter_by_author": "Filter by author",
  "explore.loading": "Loading...",
  "explore.retry": "Retry loading",
  "explore.no_stories": "No stories found",
  "explore.search_placeholder": "Search story titles, descriptions, tags or author addresses...",
  "explore.search_results": "Found {count} stories",
  "explore.search_contains": "containing \"{term}\"",
  "explore.clear_search": "Clear",
  "explore.clear_search_tooltip": "Clear search (Esc)",
  "explore.sort_by": "Sort by:",
  "explore.sort_latest": "Latest Created",
  "explore.sort_popular": "Most Popular",
  "explore.sort_tips": "Most Tipped",
  "explore.total_stories": "Total {count} stories",
  "explore.load_error": "Failed to load stories: {error}",
  "explore.retry_button": "Retry",
  "explore.loading_stories": "Loading stories...",
  "explore.story_alt": "Story #{id}",
  "explore.error_load_failed": "Failed to load story info: {error}",
  "explore.error_notification": "Story #{id} metadata loading failed",
  "explore.retry_load": "Retry loading",
  "explore.read_button": "Read",
  "explore.no_stories_found": "No matching stories found",
  "explore.search_suggestions": "Try different keywords, or",
  "explore.clear_conditions": "clear search conditions",
  "explore.suggested_searches": "Suggested searches:",
  "explore.tag_scifi": "Sci-fi",
  "explore.tag_adventure": "Adventure",
  "explore.tag_story": "Story",
  "explore.no_stories_yet": "No stories yet",
  "explore.be_first_creator": "Be the first to create a story!",
  "explore.create_tooltip": "Create Story",

  // Fork page
  "fork.title": "Create new story branch based on existing chapter",
  "fork.original_story": "Original Story",
  "fork.create_fork": "Create Fork",
  "fork.new_title": "New Story Title",
  "fork.new_content": "New Story Content",

  // Comment system
  "comment.title": "Comments",
  "comment.add": "Post Comment",
  "comment.adding": "Posting...",
  "comment.connect_wallet": "Please connect wallet to comment",
  "comment.empty": "No comments yet, be the first to comment!",
  "comment.placeholder": "Write your comment...",
  "comment.placeholder_story": "Say something about this story...",
  "comment.placeholder_chapter": "Say something about this chapter...",
  "comment.loading": "Loading comment content from IPFS...",

  // IPFS content display
  "ipfs.load_failed": "Load failed",
  "ipfs.load_content_failed": "Failed to load IPFS content",
  "ipfs.load_preview_failed": "Failed to load preview",
  "ipfs.copy_cid": "Copy CID",
  "ipfs.copy_link": "Copy Link",
  "ipfs.title_label": "Title",
  "ipfs.description_label": "Description",
  "ipfs.content_label": "Content",
  "ipfs.author_label": "Author",
  "ipfs.created_time_label": "Created Time",
  "ipfs.attributes_label": "Attributes",
  "ipfs.tags_label": "Tags",

  // IPFS upload
  "upload.file_size_exceeded": "File size cannot exceed {size}MB",
  "upload.upload_failed": "Upload failed",
  "upload.click_or_drag": "Click to upload or drag files here",
  "upload.supported_types": "Supports image, text, JSON and other file types",
  "upload.max_file_size": "Max file size: {size}MB",
  "upload.select_image_file": "Please select an image file",
  "upload.image_size_exceeded": "Image size cannot exceed 5MB",
  "upload.image_upload_failed": "Image upload failed",
  "upload.preview": "Preview",
  "upload.image_formats": "PNG, JPG, GIF (Max 5MB)",

  // Like system
  "like.liked": "Liked",
  "like.like": "Like",
  "like.connect_wallet": "Please connect wallet first",

  // Tip system
  "tip.title": "Tip",
  "tip.amount": "Tip Amount",
  "tip.send": "Send Tip",
  "tip.connect_wallet": "Please connect wallet first",
  "tip.story": "Tip Story",
  "tip.chapter": "Tip Chapter",
  "tip.story_author": "Story Author",
  "tip.chapter_author": "Chapter Author",
  "tip.support_creation": "Support quality content creation",
  "tip.select_amount": "Select tip amount",
  "tip.custom_amount": "Custom amount",
  "tip.enter_amount": "Enter amount...",
  "tip.fee_distribution": "Fee distribution:",
  "tip.author_receive": "{author}: {amount} STT",
  "tip.story_author_receive": "Story author: {amount} STT",
  "tip.chapter_author_receive": "Chapter author: {amount} STT",
  "tip.platform_fee": "Platform fee: {amount} STT",
  "tip.tipping": "Tipping...",
  "tip.success": "Tip successful!",
  "tip.failed": "Tip failed",

  // Home feature cards
  "home.feature1.title": "Start your creative journey. Each story is a unique NFT.",
  "home.feature2.title": "Explore amazing stories by other creators, discover infinite creative possibilities.",
  "home.feature3.title": "Fork stories you like, create your own story branches and endings.",

  // Story detail page specific translations
  "story.detail.back": "Back",
  "story.detail.updating": "Updating data...",
  "story.detail.story_cover": "Story Cover",
  "story.detail.story_tags": "Story Tags",
  "story.detail.story_structure": "Story Structure",
  "story.detail.total_chapters": "Total Chapters",
  "story.detail.fork_points": "Fork Points",
  "story.detail.tree_help": "Click nodes for details, use action buttons to interact",
  "story.detail.no_chapters": "No chapters yet",
  "story.detail.no_chapters_desc": "Anyone can add the first chapter to this story and start an amazing story journey",
  "story.detail.add_first_chapter": "Add First Chapter",
  "story.detail.continue_first_chapter": "Continue First Chapter",
  "story.detail.connect_wallet_desc": "Connect wallet to add the first chapter",
  "story.detail.continue_latest": "Continue Latest Chapter",
  "story.detail.fork_latest": "Fork Latest Chapter",
  "story.detail.add_chapter_tooltip": "Add new chapter (story author only)",
  "story.detail.continue_story": "Continue Story",
  "story.detail.fork_story_button": "Fork Story",
  "story.detail.fork_story_tooltip": "Create a fork based on this story",
  "story.detail.connect_wallet_actions": "Connect wallet to continue chapters or create forks",
  "story.detail.story_not_found": "Story does not exist or failed to load",
  "story.detail.load_failed": "Load Failed",
  "story.detail.retry": "Retry",

  // Chapter related translations
  "chapter.title": "Chapter {number}",
  "chapter.author_label": "Author:",
  "chapter.fork_fee_label": "Fork Fee: {fee} STT",
  "chapter.reading_detail": "Click to read detailed content",
  "chapter.forks_count": "{count} forks",
  "chapter.branches_count": "{count} branches",
  "chapter.story_fork_here": "Story forks here",
  "chapter.fork_description":
    "After Chapter {number}, there are {count} different development directions, each branch brings a different story experience. Choose the branch you're interested in to continue reading:",
  "chapter.select_branch": "Select Branch ({count})",
  "chapter.branch_label": "Branch {letter}",
  "chapter.read_chapter": "Read Chapter",
  "chapter.continue_chapter": "Continue",
  "chapter.fork_chapter": "Fork",
  "chapter.tip_chapter": "Tip",
  "chapter.connect_wallet_tip": "Please connect wallet first",
  "chapter.tip_tooltip": "Tip the chapter author",
  "chapter.continue_tooltip": "Continue this chapter",
  "chapter.fork_tooltip_base": "Create fork based on this chapter",
  "chapter.fork_tooltip_fee": "Create fork based on this chapter (requires {fee} STT)",
  "chapter.fork_fee_badge": "{fee} STT",
  "chapter.only_author_continue": "Only chapter author can continue their own chapter",
  "chapter.only_latest_continue": "Only the latest chapter can be continued",
  "chapter.continue_this_chapter": "Continue this chapter",
  "chapter.has_forks": "This chapter has {count} forks",
  "chapter.loading_title": "⚠️ Chapter title loading...",
  "chapter.loading_content": "Loading chapter title...",
  "chapter.retry_loading": "Reload chapter information",
  "chapter.loading_error_new": "New chapters may need a few minutes to sync, please try again later",
  "chapter.info_loading": "📖 Chapter information loading...",
  "chapter.reloading": "Reloading chapter information...",

  // Modal translations
  "modal.add_chapter.title": "Add New Chapter",
  "modal.add_chapter.chapter_title": "Chapter Title *",
  "modal.add_chapter.chapter_content": "Chapter Content *",
  "modal.add_chapter.title_placeholder": "Enter chapter title...",
  "modal.add_chapter.content_placeholder": "Continue your story...",
  "modal.add_chapter.fork_fee": "Fork Fee",
  "modal.add_chapter.fork_fee_unit": "STT",
  "modal.add_chapter.chapter_image": "Chapter Image",
  "modal.add_chapter.creating": "Creating...",
  "modal.add_chapter.create": "Create Chapter",
  "modal.continue_chapter.title": "Continue Chapter - Chapter {number}",
  "modal.continue_chapter.based_on": "Based on chapter:",
  "modal.continue_chapter.content_placeholder": "Continue this story...",
  "modal.continue_chapter.fork_fee_desc": "STT (required when others continue this chapter)",
  "modal.continue_chapter.continuing": "Continuing...",
  "modal.continue_chapter.continue": "Continue Chapter",
  "modal.fork_chapter.title": "Create Chapter Fork",
  "modal.fork_chapter.fork_title": "Fork Chapter Title *",
  "modal.fork_chapter.fork_content": "Fork Content *",
  "modal.fork_chapter.title_placeholder": "Enter fork chapter title...",
  "modal.fork_chapter.content_placeholder": "Start your fork chapter here...",
  "modal.fork_chapter.fork_fee_desc": "STT (required when others continue this fork chapter)",
  "modal.fork_chapter.chapter_note": "Will create a new chapter branch, still belongs to current story",
  "modal.fork_chapter.fee_required": "Fork fee required",
  "modal.fork_chapter.fee_description": "Forking this chapter requires {fee} STT",
  "modal.fork_chapter.forking": "Forking...",
  "modal.fork_chapter.fork_button": "Create Chapter Fork",
  "modal.fork_chapter.fork_button_fee": "Pay {fee} STT and Create Fork",

  // Error and success messages
  "error.wallet_connect_required": "Please connect wallet first",
  "error.title_content_required": "Title and content cannot be empty",
  "error.chapter_not_exist": "Chapter does not exist",
  "error.only_author_continue": "Only chapter author can continue their own chapter",
  "error.chapter_create_failed": "Create failed",
  "error.chapter_continue_failed": "Continue failed",
  "error.chapter_fork_failed": "Fork failed",
  "error.tip_failed": "Tip failed",
  "error.metadata_load_failed": "Failed to load chapter metadata",
  "success.chapter_created": "Chapter created successfully!",
  "success.chapter_continued": "Chapter continued successfully!",
  "success.chapter_forked": "Chapter forked successfully!",
  "prompt.tip_amount": "Please enter tip amount (STT):",
  "prompt.fork_confirm": "Forking this chapter requires {fee} STT to the original author. Are you sure to continue?",

  // Chapter reading page specific translations
  "chapter.read.loading": "Loading chapter...",
  "chapter.read.not_found": "Chapter not found",
  "chapter.read.back_to_story": "Back to Story",
  "chapter.read.previous": "Previous Chapter",
  "chapter.read.next": "Next Chapter",
  "chapter.read.tip": "Tip",
  "chapter.read.continue": "Continue",
  "chapter.read.fork": "Fork",
  "chapter.read.story_number": "Story #{id}",
  "chapter.read.chapter_number": "Chapter {number}",
  "chapter.read.story_fork_point": "Story Fork Point",
  "chapter.read.fork_description":
    "There are {count} different story development directions here, choose one to continue reading:",
  "chapter.read.branch_label": "Branch {number}",
  "chapter.read.current": "Current",
  "chapter.read.click_to_read": "Click to read this branch",
  "chapter.read.tip_earned": "{amount} STT",
  "chapter.read.next_branches": "Next Chapter ({count})",
  "chapter.read.invalid_content_id": "Invalid content identifier",
  "chapter.read.content_empty": "Content is empty",
  "chapter.read.load_content_failed": "Failed to load content",
  "chapter.read.chapter_image": "Chapter illustration",
  "chapter.read.get_data_failed": "Failed to get data",
  "chapter.read.load_story_metadata_failed": "Failed to load story metadata",
  "chapter.read.get_chapters_failed": "Failed to get chapters data",
  "chapter.read.connect_wallet_first": "Please connect wallet first",
  "chapter.read.input_tip_amount": "Enter tip amount (STT):",
  "chapter.read.tip_success": "Tip successful!",
  "chapter.read.tip_failed": "Tip failed",
  "chapter.read.return_to_story": "Return to story page",
  "chapter.read.connect_wallet_tip": "Please connect wallet first",
  "chapter.read.tip_author": "Tip the chapter author",

  // Fork page
  "fork.missing_story_id": "Missing story ID parameter",
  "fork.original_content_not_found": "Original content not found or failed to load",
  "fork.back": "Back",
  "fork.chapter_subtitle": "Create new story branch based on existing chapter",
  "fork.story_subtitle": "Create new story line based on existing story",
  "fork.fee_required_title": "Fork fee required",
  "fork.fee_required_desc": "Forking this {type} requires {fee} STT to the original author",
  "fork.original_story": "Original Story",
  "fork.original_chapter": "Original Chapter",
  "fork.likes": "likes",
  "fork.forks": "forks",
  "fork.fork_fee_label": "Fork fee",
  "fork.create_fork": "Create Fork",
  "fork.basic_info": "Basic Information",
  "fork.fork_title": "Fork Title *",
  "fork.fork_title_placeholder": "Give your fork a title...",
  "fork.fork_content": "Fork Content *",
  "fork.fork_content_placeholder": "Continue this story...",
  "fork.characters": "characters",
  "fork.chapter_illustration": "Chapter Illustration",
  "fork.economic_settings": "Economic Settings",
  "fork.my_fork_fee": "My Fork Fee",
  "fork.fork_fee_description": "Fee that others need to pay to fork your content",
  "fork.fee_distribution": "Fee distribution:",
  "fork.you_pay": "You need to pay: {fee} STT",
  "fork.story_author_gets": "Story author will get: {amount} STT",
  "fork.chapter_author_gets": "Chapter author will get: {amount} STT",
  "fork.platform_fee": "Platform fee: {amount} STT",
  "fork.forking": "Forking...",
  "fork.create_fork_button": "Create Fork",
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>("en");

  // 初始化语言
  useEffect(() => {
    const savedLanguage = localStorage.getItem("storychain-language") as Language;
    if (savedLanguage && (savedLanguage === "zh" || savedLanguage === "en")) {
      setLanguageState(savedLanguage);
    } else {
      // 检测浏览器语言
      const browserLanguage = navigator.language.toLowerCase();
      if (browserLanguage.includes("zh")) {
        setLanguageState("zh");
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("storychain-language", lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    const translations = language === "zh" ? zhTranslations : enTranslations;
    let translation = translations[key] || key;

    // 如果有参数，进行替换
    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        translation = translation.replace(new RegExp(`\\{${paramKey}\\}`, "g"), String(paramValue));
      });
    }

    return translation;
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
